/* eslint-disable jsx-a11y/alt-text */
'use client'

import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer'

// Define the Clinical/Architectural Style
const styles = StyleSheet.create({
  page: {
    padding: 40,
    backgroundColor: '#FFFFFF',
    fontFamily: 'Helvetica', // Fallback font that is safe for web PDF
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
    borderBottom: '1pt solid #b5a642',
    paddingBottom: 10
  },
  brandTitle: {
    fontSize: 10,
    color: '#1b270e', // Dark Green
    textTransform: 'uppercase',
    letterSpacing: 2
  },
  date: {
    fontSize: 10,
    color: '#b5a642' // Gold
  },
  section: {
    marginBottom: 20
  },
  title: {
    fontSize: 24,
    color: '#1b270e',
    marginBottom: 5,
    fontFamily: 'Helvetica-Bold'
  },
  subtitle: {
    fontSize: 12,
    color: '#666',
    marginBottom: 20
  },
  scoreBlock: {
    flexDirection: 'row',
    backgroundColor: '#1b270e',
    padding: 20,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 30
  },
  scoreVal: {
    color: '#b5a642',
    fontSize: 36,
    fontFamily: 'Helvetica-Bold'
  },
  scoreLabel: {
    color: '#c9ccbb',
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: 1
  },
  profileBadge: {
    backgroundColor: '#b5a642',
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 4,
    marginTop: 5
  },
  profileText: {
    color: '#1b270e',
    fontSize: 10,
    fontFamily: 'Helvetica-Bold',
    textTransform: 'uppercase'
  },
  domainRow: {
    flexDirection: 'row',
    borderBottom: '1pt solid #eee',
    paddingBottom: 8,
    marginBottom: 8
  },
  domainName: {
    width: '40%',
    fontSize: 11,
    color: '#1b270e',
    fontFamily: 'Helvetica-Bold'
  },
  domainScore: {
    width: '15%',
    fontSize: 11,
    color: '#b5a642',
    textAlign: 'right'
  },
  domainDesc: {
    width: '45%',
    fontSize: 10,
    color: '#555',
    paddingLeft: 10,
    lineHeight: 1.4
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    fontSize: 8,
    color: '#ccc',
    borderTop: '1pt solid #eee',
    paddingTop: 10
  }
})

interface ReportProps {
  displayName: string
  score: number
  systemState: string
  profile: string
  domains: any[]
}

// The Document Component
export const NeuroReportPDF = ({ displayName, score, systemState, profile, domains }: ReportProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      
      {/* HEADER */}
      <View style={styles.header}>
        <Text style={styles.brandTitle}>The Sentient Home</Text>
        <Text style={styles.date}>{new Date().toLocaleDateString()}</Text>
      </View>

      {/* TITLE */}
      <View style={styles.section}>
        <Text style={styles.title}>Neuro-Environmental Report</Text>
        <Text style={styles.subtitle}>Prepared for {displayName}</Text>
      </View>

      {/* HERO SCORE CARD */}
      <View style={styles.scoreBlock}>
        <View>
          <Text style={styles.scoreLabel}>Current System State</Text>
          <Text style={{ color: 'white', fontSize: 16, marginTop: 4 }}>{systemState}</Text>
        </View>
        <View style={{ alignItems: 'flex-end' }}>
          <Text style={styles.scoreVal}>{score}/100</Text>
          <View style={styles.profileBadge}>
            <Text style={styles.profileText}>The {profile}</Text>
          </View>
        </View>
      </View>

      {/* DOMAIN BREAKDOWN */}
      <View style={styles.section}>
        <Text style={{ ...styles.brandTitle, marginBottom: 15, color: '#b5a642' }}>Detailed Analysis</Text>
        
        {domains.map((d) => (
          <View key={d.id} style={styles.domainRow}>
            <Text style={styles.domainName}>{d.name}</Text>
            <Text style={styles.domainScore}>{d.score}/{d.max}</Text>
            <Text style={styles.domainDesc}>{d.description}</Text>
          </View>
        ))}
      </View>

      {/* FOOTER */}
      <Text style={styles.footer}>
        This document is an environmental assessment, not a medical diagnosis. 
        Generated by The Sentient Home Algorithm.
      </Text>
    </Page>
  </Document>
)
